name: Deploy via FTP 🚀

on:
  push:
    branches:
      - master # Dispara o deploy sempre que você atualizar a branch main

jobs:
  web-deploy:
    name: 🎉 Compilar e Enviar
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Pegando o código mais recente
      uses: actions/checkout@v4

    - name: 🟢 Configurando o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: 📦 Instalar dependências
      run: npm ci

    - name: 🏗️ Compilar o projeto (Astro + React)
      run: npm run build

    - name: 🚀 Enviar via FTP para o servidor da VGT
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./dist/
        server-dir: /maxebina.com.br/www/portfolio-teste/